# Site settings
email: stubbsrw@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Rebecca Stubbs
description: Geospatial data scientist with experience in spatiotemporal modeling, public health, data analysis and visualization.
url: ""
twitter_username: 
default_img: https://avatars0.githubusercontent.com/u/7060498?v=4&s=460

# Profile settings
name: Rebecca Stubbs
profile_img: https://avatars0.githubusercontent.com/u/7060498?v=4&s=460
profile: Geospatial data scientist with experience in spatiotemporal modeling, public health, data analysis and visualization.
social:
  github: https://github.com/RebeccaStubbs/

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
include: ["_categories"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
